@Host_HostAddress = http://localhost:5178

PUT {{Host_HostAddress}}/artists
Content-Type: application/json

{
  "Name": "George Harrison"
}

> {%
    client.global.set("artistId", response.headers.valueOf('Location').split("/")[2]);
%}

###

PUT {{Host_HostAddress}}/audio-items
Content-Type: application/json

{
  "Title": "Got My Mind Set On You",
  "Artists": [
    { "Name": "George Harrison", "Id": "{{artistId}}" }
  ],
  "CategoryPaths": ["/music"]
}

> {%
    client.global.set("audioItemLocation", response.headers.valueOf('Location'));
%}

###

POST {{Host_HostAddress}}{{audioItemLocation}}/audio
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: application/octet-stream; name="audio"; filename="1ktone.wav"

< ./1ktone.wav
--WebAppBoundary--

###

DELETE {{Host_HostAddress}}{{audioItemLocation}}

###